#!/bin/bash
# This `DEBIAN/postinst` script is run post-installation
echo "Create links"
ln -s /usr/share/busylight-menu/Menu.py /usr/bin/busylight-menu
chmod a+rx /usr/share/busylight-menu/Menu.py
chmod a+rx /usr/bin/busylight-menu